### ISSUE TITLE
Only send updated files

### ISSUE THREAD

**Issue by dotnetwise** [NucleusIDE/meteor-live-update#5]
This is a must feature in order to see quickly live updates, otherwise waiting 2+ seconds makes  it useless.

**Comment by channikhabra** [comment]
Hey,

Hey,

I've rewritten this package to be used as a library for pushing code to meteor. For using hot-push in your app, please use these two: [meteor-hot-loader](https://github.com/channikhabra/meteor-hot-loader) and [channikhabra:hot-loader](https://github.com/channikhabra/channikhabra-hot-loader)

I had to create a separate `meteor-hot-loader` because of the speed issues. The reason for the speed problem is mentioned in the readme's  of above projects.

Please give it a shot some time.
